//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizdom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuestionDetail
    {
        public int UserQuestionDetailID { get; set; }
        public int UserQuestionID { get; set; }
        public string ChoiceText { get; set; }
        public bool IsCorrect { get; set; }
    
        public virtual UserQuestion UserQuestion { get; set; }
    }
}
