//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quizdom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExam
    {
        public int UserExamID { get; set; }
        public int UserID { get; set; }
        public int ExamID { get; set; }
        public Nullable<System.DateTime> AssignedAt { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual User User { get; set; }
    }
}
